apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata: 
  name: prod-issuer
spec: 
  acme:
    email: sho.obata@oracle.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: clusterissuer-pass
    solvers:
    - http01:
        ingress:
          class: nginx
