apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cso-root-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/sh-sho/cso-cloud-native-repo"
    path: kubernetes/argocd-apps
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
