apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  destination:
    namespace: ingress-nginx
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://kubernetes.github.io/ingress-nginx"
    targetRevision: 4.9.1
    chart: ingress-nginx
    helm:
      values: |
        controller:
          service:
            annotations:
              oci.oraclecloud.com/load-balancer-type: "lb"
              service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
              service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10Mbps"
              service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "30Mbps"
  project: management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
